# AUTOGENERATED! DO NOT EDIT! File to edit: ../pb_parkinsons_progression_1.ipynb.

# %% auto 0
__all__ = ['comp', 'path', 'train_peptides', 'train_proteins', 'train_clinical_data', 'supplemental_clinical_data']

from fastai.tabular.all import *

import seaborn as sns

import tqdm

pd.options.display.max_rows = 20
pd.options.display.max_columns = 8

try: import fastkaggle
except ModuleNotFoundError:
    !pip install -Uq fastkaggle

from fastkaggle import *

comp = 'amp-parkinsons-disease-progression-prediction'
path = setup_comp(comp, install='fastai')

train_peptides = pd.read_csv(path/'train_peptides.csv')
train_proteins = pd.read_csv(path/'train_proteins.csv')
train_clinical_data = pd.read_csv(path/'train_clinical_data.csv')
supplemental_clinical_data = pd.read_csv(path/'supplemental_clinical_data.csv')
