# AUTOGENERATED! DO NOT EDIT! File to edit: ../pb_parkinsons_prog.ipynb.

# %% auto 0
__all__ = ['comp', 'path', 'df_train_proteins']

# %% ../pb_parkinsons_prog.ipynb 7
from fastai.tabular.all import *

pd.options.display.max_rows = 20
pd.options.display.max_columns = 8

# %% ../pb_parkinsons_prog.ipynb 8
try: import fastkaggle
except ModuleNotFoundError:
    !pip install -Uq fastkaggle

from fastkaggle import *

# %% ../pb_parkinsons_prog.ipynb 10
comp = 'amp-parkinsons-disease-progression-prediction'
path = setup_comp(comp, install='fastai')

# %% ../pb_parkinsons_prog.ipynb 11
df_train_proteins = pd.read_csv(path/"train_proteins.csv")
